import type {Metadata} from 'next';
import {Geist, Geist_Mono, Bricolage_Grotesque} from 'next/font/google';
import './globals.css';
import OnboardingContextProvider from '@/context/OnboardingContext';
import ReactQueryProvider from '@/context/ReactQueryContext';
import {Toaster} from '@/components/ui/sonner';
// PAYMENT DISABLED - StripeContext commented out until paid plan is re-enabled
// import StripeContext from "@/context/StripeContext";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const bricolageGrotesque = Bricolage_Grotesque({
    variable: '--font-bricolage-grotesque',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'My Hub Application',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${bricolageGrotesque.variable} antialiased`}
        >
        <ReactQueryProvider>
            {/* PAYMENT DISABLED - StripeContext wrapper commented out until paid plan is re-enabled */}
            {/* <StripeContext> */}
                <OnboardingContextProvider>{children}</OnboardingContextProvider>
            {/* </StripeContext> */}
        </ReactQueryProvider>
        <Toaster/>
        </body>
        </html>
    );
}
